export const book1Cast = {
  main: [
    {
      name: "Wesley Johnson",
      slug: "wesley",
      image: "/wesley.jpg",
      role: "Protagonist",
    },
    {
      name: "Gavin Summers",
      slug: "gavin",
      image: "/gavin.jpg",
      role: "Co-Protagonist",
    },
    {
      name: "Danny Foster",
      slug: "danny",
      image: "/danny.jpg",
      role: "Co-Protagonist",
    },
    {
      name: "Jade Stone",
      slug: "jade",
      image: "/jade.jpg",
      role: "Co-Protagonist",
    },
    {
      name: "Keith Powers",
      slug: "keith",
      image: "/keith.jpg",
      role: "Co-Protagonist",
    },
    {
      name: "William Hutton",
      slug: "william",
      image: "/william.jpg",
      role: "Secondary",
    },
    {
      name: "Valeria Adair-Taylor",
      slug: "valeria",
      image: "/valeria.jpg",
      role: "Secondary",
    },
    {
      name: "Ajax Johnson",
      slug: "ajax",
      image: "/ajax.jpg",
      role: "Secondary",
    },
    {
      name: "Zoey Pierce-Harris",
      slug: "zoey",
      image: "/zoey.jpg",
      role: "Secondary",
    },
  ],

  supporting: [
    {
      name: "Samantha Clark",
      slug: "samantha",
      image: "/samantha.jpg",
      role: "Supporting",
      comingSoon: true,
    },
    {
      name: "Ciara Jackson",
      slug: "ciara",
      image: "/ciara.jpg",
      role: "Supporting",
      comingSoon: true,
    },
    {
      name: "Ezequiel Figueroa",
      slug: "ezequiel",
      image: "/ezequiel.jpg",
      role: "Supporting",
      comingSoon: true,
    },
    {
      name: "Mary Santiago",
      slug: "mary",
      image: "/mary.jpg",
      role: "Supporting",
      comingSoon: true,
    },
    {
      name: "Kiely Robinson",
      slug: "kiely",
      image: "/kiely.jpg",
      role: "Supporting",
      comingSoon: true,
    },
    {
      name: "Andrew Torres",
      slug: "andrew",
      image: "/andrew.jpg",
      role: "Supporting",
      comingSoon: true,
    },
    {
      name: "Robert Garcia",
      slug: "robert",
      image: "/robert.jpg",
      role: "Supporting",
      comingSoon: true,
    },
    {
      name: "Justin Frasier",
      slug: "justin",
      image: "/justin.jpg",
      role: "Supporting",
      comingSoon: true,
    },
  ],

  antagonists: [
    {
      name: "Shi",
      slug: "shi",
      image: "/stephen.jpg",
      role: "Antagonist",
      comingSoon: true,
    },
    {
      name: "Aiden Summers",
      slug: "aiden",
      image: "/aiden.jpg",
      role: "Antagonist",
      comingSoon: true,
    },
    {
      name: "Nolan Khan",
      slug: "nolan",
      image: "/nolan.jpg",
      role: "Antagonist",
      comingSoon: true,
    },
    {
      name: "Enzo Antonov",
      slug: "enzo",
      image: "/enzo.jpg",
      role: "Antagonist",
      comingSoon: true,
    },
    {
      name: "Talia Yassin",
      slug: "talia",
      image: "/talia.jpg",
      role: "Antagonist",
      comingSoon: true,
    },
    {
      name: "Celeste Masters",
      slug: "celeste",
      image: "/celeste.jpg",
      role: "Antagonist",
      comingSoon: true,
    },
    {
      name: "Azazel Pierce",
      slug: "azazel",
      image: "/azazel.jpg",
      role: "Antagonist",
      comingSoon: true,
    },
    {
      name: "Axel Pierce",
      slug: "axel",
      image: "/axel.jpg",
      role: "Antagonist",
      comingSoon: true,
    },
  ],
};
